name: Mirror Image

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
    inputs:
      image:
        description: '镜像地址'
        required: true
      name:
        required: true
        description: '新镜像名称'

env:
  
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # k8s.gcr.io/dns/dns-local-cache:v1.7.0
  IMAGE_NAME: ${{ github.event.inputs.image }}
  # new image name
  NEW_IMAGE_NAME: MittWillson/${{ github.event.inputs.name }}

jobs:
  mirror:
    name: Mirror ${{ github.event.inputs.image }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          docker pull ${IMAGE_NAME}
          docker image tag ${IMAGE_NAME} ${REGISTRY}/${NEW_IMAGE_NAME}
          docker push ${REGISTRY}/${NEW_IMAGE_NAME}